FROM python:3.11-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV TF_ENABLE_ONEDNN_OPTS 3


WORKDIR /app
COPY requirements.txt pyproject.toml poetry.lock entrypoint.sh ./

RUN pip install --upgrade pip
RUN pip3 --no-cache-dir install -r requirements.txt
RUN poetry config virtualenvs.create false
RUN poetry install

ADD . /app/

CMD ["celery", "-A", "app.worker.celery_app", "beat", "-l", "info"]