apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.service.name }}-worker"
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ printf "%s" (toString $value) | b64enc }}
  {{- end }}