apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc-elt
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi